filebeat.inputs:
  - type: filestream
    id: keycloak-container-logs
    paths:
      - '/var/lib/docker/containers/*/*.log'
    parsers:
      - container:
          stream: all
          format: auto
    processors:
      - add_docker_metadata:
          host: 'unix:///var/run/docker.sock'
      - add_fields:
          target: ''
          fields:
            service.name: keycloak
            service.type: identity

output.elasticsearch:
  hosts: ['http://host.docker.internal:9200']
  username: 'elastic'
  password: 'Tn99rhPs'
  index: 'filebeat-keycloak-%{+yyyy.MM.dd}'

setup.ilm.enabled: false
setup.template.name: 'filebeat-keycloak'
setup.template.pattern: 'filebeat-keycloak-*'

logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644
