receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 5s
    send_batch_size: 512
  batch/metrics:
    timeout: 60s
    send_batch_size: 512
  elasticapm: {}
  resource:
    attributes:
      - key: deployment.environment
        value: ${env:ELASTIC_APM_ENVIRONMENT}
        action: upsert

connectors:
  elasticapm: {}

extensions:
  apmconfig:
    source:
      elasticsearch:
        endpoint: http://${env:ELASTIC_USERNAME}:${env:ELASTIC_PASSWORD}@elasticsearch:9200
        cache_duration: 30s
    opamp:
      protocols:
        http:
          endpoint: 0.0.0.0:4320
  health_check:
    endpoint: :13133

exporters:
  elasticsearch/otel:
    endpoints:
      - ${env:ELASTIC_ENDPOINT}
    user: ${env:ELASTIC_USERNAME}
    password: ${env:ELASTIC_PASSWORD}
    mapping:
      mode: otel

service:
  extensions: [apmconfig, health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, elasticapm, resource]
      exporters: [elasticapm, elasticsearch/otel]
    metrics:
      receivers: [otlp]
      processors: [batch/metrics, resource]
      exporters: [elasticsearch/otel]
    logs:
      receivers: [otlp]
      processors: [batch, resource]
      exporters: [elasticapm, elasticsearch/otel]
    metrics/aggregated-otel-metrics:
      receivers: [elasticapm]
      processors: []
      exporters: [elasticsearch/otel]
